apiVersion: v1
kind: ConfigMap
metadata:
  name: trussihealth-api-configmap
data:
  APP_ENV: "deployment"
  PORT: "8082"
  ISSUER_DID: "did:ethr:0x9A668DBe392230c407beC406CC4bb965C16CAbee"
  VIDCHAIN_API: "https://labs.vidchain.net"

