trigger:
  branches:
    include:
      - main
pr: none

resources:
  - repo: self

variables:
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  Repo: 'trussihealth-api'
  RepoEndpoint: 'k8scrvidchainlabs.azurecr.io/trussihealth-api'
  # Repository directory
  dir: '.'
  # Dockerfile
  Dockerfile: '$(dir)/Dockerfile'
  # Kubernetes YAML
  k8s: '$(dir)/k8s/k8s-labs.yml'
  # Configmaps
  configMap: '$(dir)/k8s/configmap-labs.yml'
  # Kubernetes namespace
  namespace: 'labs'
  # Image tagging: application version - build
  tag: $(Build.BuildNumber)
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # run unit test: true/false
  runUnitTests: 'true'
  # test run title
  testRunName: '[labs] trussihealth-api unit tests'

stages:
  - stage: UnitTests
    displayName: 'Unit test stage'
    jobs:
      - job: SetCommitHashAsBuildNumber
        displayName: 'Set build number to commit hash'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                commit=$(Build.SourceVersion)
                shortCommit=${commit:0:7}
                echo "##vso[build.updatebuildnumber]commit.$shortCommit"
            displayName: 'set commit hash'
      - job: RunUnitTests
        displayName: 'Run unit tests: $(variables.runUnitTests)'
        pool:
          vmImage: $(vmImageName)
        condition: eq('${{ variables.runUnitTests}}', 'true')
        steps:
          - task: GoTool@0
            displayName: 'Use Go 1.20.3'
            inputs:
              version: '1.20.3'
          - task: Go@0
            displayName: 'Go get'
            inputs:
              command: 'get'
              workingDirectory: '$(dir)/src'
          - task: Go@0
            displayName: 'Go test'
            inputs:
              command: 'custom'
              customCommand: 'go test -v $(dir)/tests/packages/...'
  - stage: 'Build'
    jobs:
      - job: Build
        displayName: 'Build trussihealth-api'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Login ACR
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)
          - script: 'docker pull $(RepoEndpoint):latest'
            displayName: Pull latest for layer caching
            continueOnError: true # for first build, no cache
          - task: Docker@2
            displayName: 'build --cache-from=$(RepoEndpoint):latest'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(Repo)'
              command: 'build'
              Dockerfile: $(Dockerfile)
              arguments: '--cache-from=$(RepoEndpoint):latest'
              tags: |
                $(tag)
                latest
          - task: Docker@2
            displayName: 'push'
            inputs:
              command: push
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: $(Repo)
              tags: |
                $(tag)
                latest
  - stage: Deploy
    displayName: 'Deploy stage'
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: 'Deploy trussihealth-api'
        pool:
          vmImage: $(vmImageName)
        environment: 'labs'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1
                - task: Kubernetes@1
                  displayName: Create/update configmap
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
                    azureResourceGroup: $(azureResourceGroup)
                    kubernetesCluster: $(kubernetesCluster)
                    command: apply
                    arguments: -f $(configMap) -n $(namespace)
                - task: KubernetesManifest@0
                  displayName: Create/update deployment
                  inputs:
                    kubernetesServiceConnection: $(kubernetesServiceConnection)
                    namespace: $(namespace)
                    manifests: $(k8s)
                    containers: |
                      $(RepoEndpoint):$(tag)
